using Pkg

Pkg.develop(url="/home/wester/Projects/Julia/Physics/PhysConst.jl")

Pkg.add("CSV")
Pkg.add("CurveFit")
Pkg.add("DataFrames")
Pkg.add("DataStructures")
Pkg.add("Dates")
Pkg.add("ForwardDiff")
Pkg.add("HDF5")
Pkg.add("HTTP")
Pkg.add("Interpolations")
Pkg.add("JSON3")
Pkg.add("NLopt")
Pkg.add("OrderedCollections")
Pkg.add("Printf")
Pkg.add("PyPlot")
Pkg.add("Statistics")
Pkg.add("Tables")
Pkg.add("TimeZones")
Pkg.add("SQLite")
Pkg.add("StringEncodings")
Pkg.add("Logging")
Pkg.add("LoggingExtras")
